// math1QuestionBank.ts
// 中学1年生 数学クイズの固定問題バンク(18単元 × 6問 = 108問)

import type { Question } from "@/lib/questionBank";

export const CATEGORIES = [
  "正負の数の大小と絶対値",
  "正負の数の加法・減法",
  "正負の数の乗法・除法",
  "文字式の表し方",
  "式の値(代入)",
  "一次式の計算",
  "方程式の性質と解き方",
  "一次方程式の利用",
  "比例",
  "反比例",
  "平面図形の基礎と移動",
  "作図",
  "円とおうぎ形",
  "空間図形の基礎",
  "展開図と投影図",
  "立体の表面積と体積",
  "度数分布とヒストグラム・代表値",
  "近似値・誤差・有効数字",
] as const;

export const MATH1_QUESTIONS: Question[] = [
  // 正負の数の大小と絶対値
  {
    text: "次の数の中で最も小さいのはどれ？\n-5, -2, 0, 3",
    type: "choice",
    answer: "-5",
    choices: ["-5", "-2", "0", "3"],
    explain: "負の数は絶対値が大きいほど小さくなる。-5 < -2 < 0 < 3。",
    category: "正負の数の大小と絶対値",
  },
  {
    text: "-7 の絶対値は？",
    type: "numeric",
    answer: 7,
    explain: "絶対値は数直線上での0からの距離。|-7| = 7。",
    category: "正負の数の大小と絶対値",
  },
  {
    text: "絶対値が4になる数はどれ？",
    type: "choice",
    answer: "4と-4",
    choices: ["4と-4", "4のみ", "-4のみ", "4と8"],
    explain: "0からの距離が4になる数は、正の4と負の-4の2つ。",
    category: "正負の数の大小と絶対値",
  },
  {
    text: "-3 と -8 では、どちらが大きい？",
    type: "choice",
    answer: "-3",
    choices: ["-3", "-8", "同じ", "比べられない"],
    explain: "負の数は絶対値が小さいほど大きい。|-3|=3 < |-8|=8 なので -3 の方が大きい。",
    category: "正負の数の大小と絶対値",
  },
  {
    text: "数直線上で0より左にある数を何という？",
    type: "choice",
    answer: "負の数",
    choices: ["負の数", "正の数", "絶対値", "自然数"],
    explain: "0より小さい数を負の数といい、負の符号(-)をつけて表す。",
    category: "正負の数の大小と絶対値",
  },
  {
    text: "-4, 1, -1, 3 を小さい順に並べたとき、2番目にくる数はどれ？",
    type: "choice",
    answer: "-1",
    choices: ["-4", "-1", "1", "3"],
    explain: "小さい順に並べると -4, -1, 1, 3。2番目は -1。",
    category: "正負の数の大小と絶対値",
  },

  // 正負の数の加法・減法
  {
    text: "(+3) + (-8) = ?",
    type: "numeric",
    answer: -5,
    explain: "符号が異なる数の和は、絶対値の大きい方から小さい方をひき、絶対値の大きい方の符号をつける。8-3=5、符号は-なので-5。",
    category: "正負の数の加法・減法",
  },
  {
    text: "(-4) - (-9) = ?",
    type: "numeric",
    answer: 5,
    explain: "ひく数の符号を変えてたす。(-4) - (-9) = (-4) + (+9) = 5。",
    category: "正負の数の加法・減法",
  },
  {
    text: "(-6) + (-2) = ?",
    type: "numeric",
    answer: -8,
    explain: "符号が同じ数の和は、絶対値の和に共通の符号をつける。6+2=8、符号は-なので-8。",
    category: "正負の数の加法・減法",
  },
  {
    text: "5 - 12 = ?",
    type: "numeric",
    answer: -7,
    explain: "5 - 12 = 5 + (-12) = -7。",
    category: "正負の数の加法・減法",
  },
  {
    text: "(-3) + 7 - 5 = ?",
    type: "numeric",
    answer: -1,
    explain: "順に計算する。(-3) + 7 = 4、4 - 5 = -1。",
    category: "正負の数の加法・減法",
  },
  {
    text: "次のうち、計算結果が正の数になるのはどれ？",
    type: "choice",
    answer: "(-5)+8",
    choices: ["(-2)+(-3)", "4-9", "(-5)+8", "(-6)-(-1)"],
    explain: "(-5)+8=3で正の数。他はすべて-5になる。",
    category: "正負の数の加法・減法",
  },

  // 正負の数の乗法・除法
  {
    text: "(-3) × (-4) = ?",
    type: "numeric",
    answer: 12,
    explain: "負の数どうしの積は正の数になる。3×4=12。",
    category: "正負の数の乗法・除法",
  },
  {
    text: "(-2) × 6 = ?",
    type: "numeric",
    answer: -12,
    explain: "符号が異なる数の積は負の数になる。2×6=12、符号は-。",
    category: "正負の数の乗法・除法",
  },
  {
    text: "(-24) ÷ (-4) = ?",
    type: "numeric",
    answer: 6,
    explain: "負の数どうしの商は正の数になる。24÷4=6。",
    category: "正負の数の乗法・除法",
  },
  {
    text: "(-2)³ の値は？",
    type: "numeric",
    answer: -8,
    explain: "(-2)×(-2)×(-2) = 4×(-2) = -8。負の数の奇数乗は負になる。",
    category: "正負の数の乗法・除法",
  },
  {
    text: "(-3)² の値は？",
    type: "numeric",
    answer: 9,
    explain: "(-3)×(-3) = 9。負の数の偶数乗は正になる。",
    category: "正負の数の乗法・除法",
  },
  {
    text: "次のうち、計算結果が負になるのはどれ？",
    type: "choice",
    answer: "(-2)³",
    choices: ["(-2)³", "(-2)²", "(-3)×(-3)", "(-8)÷(-2)"],
    explain: "(-2)³=-8で負の数。他はすべて正の数になる。",
    category: "正負の数の乗法・除法",
  },

  // 文字式の表し方
  {
    text: "「a × 5」を文字式の表し方の決まりにしたがって書くと？",
    type: "choice",
    answer: "5a",
    choices: ["5a", "a5", "5×a", "a×5"],
    explain: "文字式では数を文字の前に書き、乗法の記号×は省略する。",
    category: "文字式の表し方",
  },
  {
    text: "「x ÷ 4」を文字式の表し方の決まりにしたがって書くと？",
    type: "choice",
    answer: "x/4",
    choices: ["x/4", "4/x", "4x", "x4"],
    explain: "除法は分数の形で表す。x÷4 は x/4 と書く。",
    category: "文字式の表し方",
  },
  {
    text: "「1 × a」を文字式の表し方の決まりにしたがって書くと？",
    type: "choice",
    answer: "a",
    choices: ["a", "1a", "a1", "a×1"],
    explain: "文字の前の1は省略する。1×a は a と書く。",
    category: "文字式の表し方",
  },
  {
    text: "「a × b × (-1)」を文字式の表し方の決まりにしたがって書くと？",
    type: "choice",
    answer: "-ab",
    choices: ["-ab", "ab-", "-1ab", "ab(-1)"],
    explain: "-1は符号の-だけを残し、文字はアルファベット順に並べる。",
    category: "文字式の表し方",
  },
  {
    text: "「x × x」を指数を使って表すと？",
    type: "choice",
    answer: "x²",
    choices: ["x²", "2x", "x+x", "xx"],
    explain: "同じ文字の積は指数を使ってまとめる。x×x = x²。",
    category: "文字式の表し方",
  },
  {
    text: "100円のノートを a冊買うときの代金を表す式は？",
    type: "choice",
    answer: "100a円",
    choices: ["100a円", "100+a円", "100÷a円", "a-100円"],
    explain: "(1冊の値段)×(冊数)で代金が求まる。数を文字の前に書いて100a円。",
    category: "文字式の表し方",
  },

  // 式の値(代入)
  {
    text: "x = 3 のとき、2x + 1 の値は？",
    type: "numeric",
    answer: 7,
    explain: "2×3+1 = 6+1 = 7。",
    category: "式の値(代入)",
  },
  {
    text: "a = -2 のとき、a² の値は？",
    type: "numeric",
    answer: 4,
    explain: "(-2)² = (-2)×(-2) = 4。",
    category: "式の値(代入)",
  },
  {
    text: "x = -4 のとき、-x + 3 の値は？",
    type: "numeric",
    answer: 7,
    explain: "-(-4)+3 = 4+3 = 7。",
    category: "式の値(代入)",
  },
  {
    text: "a = 5, b = -2 のとき、a + 2b の値は？",
    type: "numeric",
    answer: 1,
    explain: "5 + 2×(-2) = 5 + (-4) = 1。",
    category: "式の値(代入)",
  },
  {
    text: "x = -3 のとき、x² - 2x の値は？",
    type: "numeric",
    answer: 15,
    explain: "(-3)² - 2×(-3) = 9 - (-6) = 9+6 = 15。",
    category: "式の値(代入)",
  },
  {
    text: "a = 6 のとき、12/a の値は？",
    type: "numeric",
    answer: 2,
    explain: "12÷6 = 2。",
    category: "式の値(代入)",
  },

  // 一次式の計算
  {
    text: "3x + 5x を計算すると？",
    type: "choice",
    answer: "8x",
    choices: ["8x", "8x²", "15x", "x8"],
    explain: "文字の部分が同じ項どうしは、係数をたして1つにまとめる。3+5=8。",
    category: "一次式の計算",
  },
  {
    text: "7a - 2a を計算すると？",
    type: "choice",
    answer: "5a",
    choices: ["5a", "5", "9a", "14a"],
    explain: "係数どうしをひく。7-2=5。",
    category: "一次式の計算",
  },
  {
    text: "2(x + 3) を計算すると？",
    type: "choice",
    answer: "2x+6",
    choices: ["2x+6", "2x+3", "x+6", "2x+5"],
    explain: "分配法則を使う。2×x + 2×3 = 2x+6。",
    category: "一次式の計算",
  },
  {
    text: "(6x - 4) ÷ 2 を計算すると？",
    type: "choice",
    answer: "3x-2",
    choices: ["3x-2", "3x-4", "6x-2", "3x-1"],
    explain: "6x÷2=3x、-4÷2=-2 なので 3x-2。",
    category: "一次式の計算",
  },
  {
    text: "4x + 3 - 2x + 5 を計算すると？",
    type: "choice",
    answer: "2x+8",
    choices: ["2x+8", "2x+3", "6x+8", "2x-2"],
    explain: "文字の項どうし、数の項どうしをそれぞれまとめる。4x-2x=2x、3+5=8。",
    category: "一次式の計算",
  },
  {
    text: "-(3x - 2) を計算すると？",
    type: "choice",
    answer: "-3x+2",
    choices: ["-3x+2", "-3x-2", "3x-2", "-3x"],
    explain: "かっこの前の-は、かっこの中の各項の符号を変える。-3x, +2。",
    category: "一次式の計算",
  },

  // 方程式の性質と解き方
  {
    text: "方程式 x + 3 = 8 を解くと、x = ?",
    type: "numeric",
    answer: 5,
    explain: "両辺から3をひくと x = 8-3 = 5。",
    category: "方程式の性質と解き方",
  },
  {
    text: "方程式 3x = 12 を解くと、x = ?",
    type: "numeric",
    answer: 4,
    explain: "両辺を3でわると x = 12÷3 = 4。",
    category: "方程式の性質と解き方",
  },
  {
    text: "方程式 2x + 5 = 13 を解くと、x = ?",
    type: "numeric",
    answer: 4,
    explain: "2x = 13-5 = 8、x = 8÷2 = 4。",
    category: "方程式の性質と解き方",
  },
  {
    text: "方程式 5x - 3 = 2x + 9 を解くと、x = ?",
    type: "numeric",
    answer: 4,
    explain: "移項すると 5x-2x = 9+3、3x = 12、x = 4。",
    category: "方程式の性質と解き方",
  },
  {
    text: "等式の両辺に同じ数をたしても、同じ数をひいても、同じ数をかけても等式が成り立つ性質を何という？",
    type: "choice",
    answer: "等式の性質",
    choices: ["等式の性質", "方程式の解", "移項", "比例式"],
    explain: "この性質を使って方程式を解いていく。",
    category: "方程式の性質と解き方",
  },
  {
    text: "方程式で、項を符号を変えて反対側の辺に移すことを何という？",
    type: "choice",
    answer: "移項",
    choices: ["移項", "代入", "展開", "約分"],
    explain: "移項するときは、項の符号(+, -)を変える。",
    category: "方程式の性質と解き方",
  },

  // 一次方程式の利用
  {
    text: "ある数xに3を足すと10になる。xの値は？",
    type: "numeric",
    answer: 7,
    explain: "x+3=10 を解くと x=7。",
    category: "一次方程式の利用",
  },
  {
    text: "1本80円の鉛筆を何本か買ったら、代金がちょうど480円だった。買った本数は？",
    type: "numeric",
    answer: 6,
    explain: "本数をxとすると 80x=480、x=480÷80=6。",
    category: "一次方程式の利用",
  },
  {
    text: "ある数の5倍から7を引くと23になる。ある数は？",
    type: "numeric",
    answer: 6,
    explain: "ある数をxとすると 5x-7=23、5x=30、x=6。",
    category: "一次方程式の利用",
  },
  {
    text: "縦が横より3cm長い長方形があり、周の長さが26cmのとき、横の長さは何cm？",
    type: "numeric",
    answer: 5,
    explain: "横をxcmとすると縦は(x+3)cm。周の長さは2{x+(x+3)}=26、4x+6=26、x=5。",
    category: "一次方程式の利用",
  },
  {
    text: "比例式 x : 12 = 3 : 4 を解くと、x = ?",
    type: "numeric",
    answer: 9,
    explain: "比例式は「内側の積 = 外側の積」。4x = 12×3 = 36、x = 9。",
    category: "一次方程式の利用",
  },
  {
    text: "生徒がx人いる。みかんを1人に4個ずつ配ると3個余り、5個ずつ配ると2個たりない。生徒の人数は？",
    type: "numeric",
    answer: 5,
    explain: "みかんの総数を2通りに表すと 4x+3=5x-2。これを解くと x=5。",
    category: "一次方程式の利用",
  },

  // 比例
  {
    text: "yはxに比例し、比例定数は3である。x=4のときのyの値は？",
    type: "numeric",
    answer: 12,
    explain: "y=3x に x=4 を代入して y=3×4=12。",
    category: "比例",
  },
  {
    text: "y=2x のグラフ上で、x=-3のときのyの値は？",
    type: "numeric",
    answer: -6,
    explain: "y=2×(-3)=-6。",
    category: "比例",
  },
  {
    text: "yはxに比例し、x=2のときy=10である。比例定数は？",
    type: "numeric",
    answer: 5,
    explain: "y=axにx=2, y=10を代入すると 10=2a、a=5。",
    category: "比例",
  },
  {
    text: "比例のグラフはどんな形になる？",
    type: "choice",
    answer: "原点を通る直線",
    choices: ["原点を通る直線", "双曲線", "放物線", "原点を通らない直線"],
    explain: "y=axのグラフは、必ず原点(0,0)を通る直線になる。",
    category: "比例",
  },
  {
    text: "yがxに比例するとき、xの値が2倍になると、yの値は何倍になる？",
    type: "numeric",
    answer: 2,
    explain: "比例定数aは一定なので、y=axのxを2倍にするとyも2倍になる。",
    category: "比例",
  },
  {
    text: "y=-4x で表される比例で、x=5のときのyの値は？",
    type: "numeric",
    answer: -20,
    explain: "y=-4×5=-20。",
    category: "比例",
  },

  // 反比例
  {
    text: "yはxに反比例し、比例定数は12である。x=3のときのyの値は？",
    type: "numeric",
    answer: 4,
    explain: "y=12/x に x=3 を代入して y=12÷3=4。",
    category: "反比例",
  },
  {
    text: "yはxに反比例し、x=2のときy=9である。比例定数は？",
    type: "numeric",
    answer: 18,
    explain: "反比例では xy=一定(比例定数)。2×9=18。",
    category: "反比例",
  },
  {
    text: "反比例 y=24/x で、x=6のときのyの値は？",
    type: "numeric",
    answer: 4,
    explain: "y=24÷6=4。",
    category: "反比例",
  },
  {
    text: "反比例のグラフを何という？",
    type: "choice",
    answer: "双曲線",
    choices: ["双曲線", "直線", "放物線", "円"],
    explain: "y=a/xのグラフは、なめらかな2つの曲線からなる双曲線になる。",
    category: "反比例",
  },
  {
    text: "yがxに反比例するとき、xの値が3倍になると、yの値は何倍になる？",
    type: "choice",
    answer: "1/3倍",
    choices: ["1/3倍", "3倍", "変わらない", "9倍"],
    explain: "xy=一定なので、xを3倍にするとyは1/3倍になる。",
    category: "反比例",
  },
  {
    text: "y=-18/x で、x=-3のときのyの値は？",
    type: "numeric",
    answer: 6,
    explain: "y=-18÷(-3)=6。",
    category: "反比例",
  },

  // 平面図形の基礎と移動
  {
    text: "2点を通り、両方向に限りなくまっすぐ伸びる線を何という？",
    type: "choice",
    answer: "直線",
    choices: ["直線", "線分", "半直線", "曲線"],
    explain: "直線は両方向に限りなく伸びる、まっすぐな線。",
    category: "平面図形の基礎と移動",
  },
  {
    text: "2点を両端とする、まっすぐな線の一部を何という？",
    type: "choice",
    answer: "線分",
    choices: ["線分", "直線", "半直線", "弧"],
    explain: "線分は2点の間をまっすぐに結んだ、長さの決まった線。",
    category: "平面図形の基礎と移動",
  },
  {
    text: "図形を一定の方向に一定の距離だけずらす移動を何という？",
    type: "choice",
    answer: "平行移動",
    choices: ["平行移動", "回転移動", "対称移動", "拡大移動"],
    explain: "平行移動では、図形の形も大きさも向きも変わらない。",
    category: "平面図形の基礎と移動",
  },
  {
    text: "図形をある点を中心に、一定の角度だけ回転させる移動を何という？",
    type: "choice",
    answer: "回転移動",
    choices: ["回転移動", "平行移動", "対称移動", "並進移動"],
    explain: "回転移動の中心となる点を回転の中心という。",
    category: "平面図形の基礎と移動",
  },
  {
    text: "図形をある直線を折り目として折り返す移動を何という？",
    type: "choice",
    answer: "対称移動",
    choices: ["対称移動", "平行移動", "回転移動", "点対称移動"],
    explain: "折り目にした直線を対称の軸という。",
    category: "平面図形の基礎と移動",
  },
  {
    text: "2直線が交わってできる4つの角のうち、向かい合う角を何という？",
    type: "choice",
    answer: "対頂角",
    choices: ["対頂角", "同位角", "錯角", "隣接角"],
    explain: "対頂角は常に等しい大きさになる。",
    category: "平面図形の基礎と移動",
  },

  // 作図
  {
    text: "線分の両端から等しい距離にある点の集まりである直線を何という？",
    type: "choice",
    answer: "垂直二等分線",
    choices: ["垂直二等分線", "角の二等分線", "垂線", "中線"],
    explain: "線分の中点を通り、その線分に垂直な直線。",
    category: "作図",
  },
  {
    text: "1つの角を2等分する半直線を何という？",
    type: "choice",
    answer: "角の二等分線",
    choices: ["角の二等分線", "垂直二等分線", "対角線", "中線"],
    explain: "角の頂点から出て、角を同じ大きさに2等分する半直線。",
    category: "作図",
  },
  {
    text: "ある直線に対して垂直に交わる直線を何という？",
    type: "choice",
    answer: "垂線",
    choices: ["垂線", "平行線", "二等分線", "接線"],
    explain: "垂線は、もとの直線と90°で交わる直線。",
    category: "作図",
  },
  {
    text: "コンパスと定規だけを使って、正確な図形をかくことを何という？",
    type: "choice",
    answer: "作図",
    choices: ["作図", "製図", "描写", "投影"],
    explain: "作図では長さを測る目盛りつき定規は使わない。",
    category: "作図",
  },
  {
    text: "円周上の1点と円の中心を結ぶ線分を何という？",
    type: "choice",
    answer: "半径",
    choices: ["半径", "直径", "弦", "弧"],
    explain: "円の中心から円周までの距離が半径。",
    category: "作図",
  },
  {
    text: "円の中心を通り、円周上の2点を結ぶ線分を何という？",
    type: "choice",
    answer: "直径",
    choices: ["直径", "半径", "弦", "接線"],
    explain: "直径は半径の2倍の長さになる。",
    category: "作図",
  },

  // 円とおうぎ形
  {
    text: "半径6cmの円の周の長さは？(円周率はπとする)",
    type: "choice",
    answer: "12πcm",
    choices: ["12πcm", "6πcm", "36πcm", "3πcm"],
    explain: "円周の長さ = 2πr = 2×π×6 = 12πcm。",
    category: "円とおうぎ形",
  },
  {
    text: "半径4cmの円の面積は？(円周率はπとする)",
    type: "choice",
    answer: "16πcm²",
    choices: ["16πcm²", "8πcm²", "4πcm²", "32πcm²"],
    explain: "円の面積 = πr² = π×4² = 16πcm²。",
    category: "円とおうぎ形",
  },
  {
    text: "円周上の2点の間にある曲線の部分を何という？",
    type: "choice",
    answer: "弧",
    choices: ["弧", "弦", "半径", "中心角"],
    explain: "弧は円周の一部分の曲線。",
    category: "円とおうぎ形",
  },
  {
    text: "円周上の2点を結ぶ線分を何という？",
    type: "choice",
    answer: "弦",
    choices: ["弦", "弧", "接線", "半径"],
    explain: "弦は円の中心を通るとは限らない、円周上の2点を結ぶ線分。",
    category: "円とおうぎ形",
  },
  {
    text: "おうぎ形で、2つの半径がつくる角を何という？",
    type: "choice",
    answer: "中心角",
    choices: ["中心角", "円周角", "対頂角", "内角"],
    explain: "おうぎ形の弧の長さや面積は中心角の大きさに比例する。",
    category: "円とおうぎ形",
  },
  {
    text: "半径9cm、中心角120°のおうぎ形の弧の長さは？(円周率はπとする)",
    type: "choice",
    answer: "6πcm",
    choices: ["6πcm", "3πcm", "9πcm", "18πcm"],
    explain: "弧の長さ = 2πr×(中心角/360) = 2π×9×(120/360) = 6πcm。",
    category: "円とおうぎ形",
  },

  // 空間図形の基礎
  {
    text: "底面が三角形で、側面が3つの長方形でできている角柱を何という？",
    type: "choice",
    answer: "三角柱",
    choices: ["三角柱", "三角錐", "四角柱", "円柱"],
    explain: "角柱は底面の形によって、三角柱、四角柱などと呼ばれる。",
    category: "空間図形の基礎",
  },
  {
    text: "底面が円で、側面が曲面、頂点が1つある立体を何という？",
    type: "choice",
    answer: "円錐",
    choices: ["円錐", "円柱", "球", "角錐"],
    explain: "円錐は底面が円で、側面が1つの曲面になっている立体。",
    category: "空間図形の基礎",
  },
  {
    text: "空間内で2つの直線が、同じ平面上になく、交わらず平行でもない位置関係を何という？",
    type: "choice",
    answer: "ねじれの位置",
    choices: ["ねじれの位置", "平行", "垂直", "交わる"],
    explain: "ねじれの位置にある2直線は、どこまで延ばしても交わらない。",
    category: "空間図形の基礎",
  },
  {
    text: "1つの直線が1つの平面と垂直に交わっているとき、その直線を平面の何という？",
    type: "choice",
    answer: "垂線",
    choices: ["垂線", "平行線", "対角線", "母線"],
    explain: "直線が平面上のすべての直線と垂直に交わるとき、平面の垂線という。",
    category: "空間図形の基礎",
  },
  {
    text: "4つの面がすべて合同な正三角形でできている立体を何という？",
    type: "choice",
    answer: "正四面体",
    choices: ["正四面体", "正六面体", "三角柱", "三角錐"],
    explain: "正四面体は、正三角形4枚でできた三角錐の一種。",
    category: "空間図形の基礎",
  },
  {
    text: "円柱は、長方形をある辺を軸として1回転させてできる立体である。この「ある辺」を含む図形は何？",
    type: "choice",
    answer: "長方形",
    choices: ["長方形", "三角形", "円", "台形"],
    explain: "長方形の1辺を軸として1回転させると円柱ができる。",
    category: "空間図形の基礎",
  },

  // 展開図と投影図
  {
    text: "立体の表面を切り開いて、平面上に広げた図を何という？",
    type: "choice",
    answer: "展開図",
    choices: ["展開図", "投影図", "立面図", "平面図"],
    explain: "展開図から、立体の面の形や数、つながり方がわかる。",
    category: "展開図と投影図",
  },
  {
    text: "立体を正面から見た図を何という？",
    type: "choice",
    answer: "立面図",
    choices: ["立面図", "平面図", "展開図", "側面図"],
    explain: "立面図は立体を正面から見たときの形を表す。",
    category: "展開図と投影図",
  },
  {
    text: "立体を真上から見た図を何という？",
    type: "choice",
    answer: "平面図",
    choices: ["平面図", "立面図", "展開図", "断面図"],
    explain: "平面図は立体を真上から見たときの形を表す。",
    category: "展開図と投影図",
  },
  {
    text: "立面図と平面図を組み合わせて、立体の形を表した図を何という？",
    type: "choice",
    answer: "投影図",
    choices: ["投影図", "展開図", "見取図", "断面図"],
    explain: "投影図は、正面から見た立面図と真上から見た平面図をセットで表す。",
    category: "展開図と投影図",
  },
  {
    text: "円柱の展開図で、側面はどんな図形になる？",
    type: "choice",
    answer: "長方形",
    choices: ["長方形", "三角形", "円", "台形"],
    explain: "円柱の側面を切り開くと長方形になり、その横の長さは底面の円周と等しい。",
    category: "展開図と投影図",
  },
  {
    text: "円錐の展開図で、側面はどんな図形になる？",
    type: "choice",
    answer: "おうぎ形",
    choices: ["おうぎ形", "長方形", "三角形", "円"],
    explain: "円錐の側面を切り開くとおうぎ形になる。",
    category: "展開図と投影図",
  },

  // 立体の表面積と体積
  {
    text: "底面積20cm²、高さ9cmの角柱の体積は？",
    type: "numeric",
    answer: 180,
    explain: "角柱の体積 = 底面積×高さ = 20×9 = 180cm³。",
    category: "立体の表面積と体積",
  },
  {
    text: "底面の半径3cm、高さ8cmの円柱の体積は？(円周率はπとする)",
    type: "choice",
    answer: "72πcm³",
    choices: ["72πcm³", "24πcm³", "72cm³", "36πcm³"],
    explain: "円柱の体積 = πr²×高さ = π×3²×8 = 72πcm³。",
    category: "立体の表面積と体積",
  },
  {
    text: "底面積15cm²、高さ6cmの三角錐の体積は？",
    type: "numeric",
    answer: 30,
    explain: "錐体の体積 = (1/3)×底面積×高さ = (1/3)×15×6 = 30cm³。",
    category: "立体の表面積と体積",
  },
  {
    text: "底面の半径3cm、高さ12cmの円錐の体積は？(円周率はπとする)",
    type: "choice",
    answer: "36πcm³",
    choices: ["36πcm³", "108πcm³", "12πcm³", "72πcm³"],
    explain: "円錐の体積 = (1/3)×πr²×高さ = (1/3)×π×3²×12 = 36πcm³。",
    category: "立体の表面積と体積",
  },
  {
    text: "半径3cmの球の体積は？(円周率はπとする)",
    type: "choice",
    answer: "36πcm³",
    choices: ["36πcm³", "27πcm³", "12πcm³", "108πcm³"],
    explain: "球の体積 = (4/3)×πr³ = (4/3)×π×27 = 36πcm³。",
    category: "立体の表面積と体積",
  },
  {
    text: "半径6cmの球の表面積は？(円周率はπとする)",
    type: "choice",
    answer: "144πcm²",
    choices: ["144πcm²", "36πcm²", "72πcm²", "288πcm²"],
    explain: "球の表面積 = 4πr² = 4×π×36 = 144πcm²。",
    category: "立体の表面積と体積",
  },

  // 度数分布とヒストグラム・代表値
  {
    text: "データを一定の区間(階級)ごとに整理した表を何という？",
    type: "choice",
    answer: "度数分布表",
    choices: ["度数分布表", "ヒストグラム", "相対度数", "代表値"],
    explain: "度数分布表は、階級ごとにデータの個数(度数)をまとめた表。",
    category: "度数分布とヒストグラム・代表値",
  },
  {
    text: "度数分布表を柱状のグラフで表したものを何という？",
    type: "choice",
    answer: "ヒストグラム",
    choices: ["ヒストグラム", "度数分布表", "折れ線グラフ", "円グラフ"],
    explain: "ヒストグラムは、階級の幅を横、度数を縦にした柱状グラフ。",
    category: "度数分布とヒストグラム・代表値",
  },
  {
    text: "各階級の度数を、全体の度数の合計で割った値を何という？",
    type: "choice",
    answer: "相対度数",
    choices: ["相対度数", "累積度数", "階級値", "度数"],
    explain: "相対度数を使うと、全体の中でその階級が占める割合がわかる。",
    category: "度数分布とヒストグラム・代表値",
  },
  {
    text: "データ 3, 5, 7, 9, 11 の平均値は？",
    type: "numeric",
    answer: 7,
    explain: "(3+5+7+9+11)÷5 = 35÷5 = 7。",
    category: "度数分布とヒストグラム・代表値",
  },
  {
    text: "データ 2, 4, 4, 6, 9 の最頻値(モード)は？",
    type: "numeric",
    answer: 4,
    explain: "最も多く出てくる値が最頻値。4が2回で最も多い。",
    category: "度数分布とヒストグラム・代表値",
  },
  {
    text: "データ 1, 3, 5, 7, 9, 11 の中央値(メジアン)は？",
    type: "numeric",
    answer: 6,
    explain: "データが6個(偶数個)のときは、中央2つの値の平均をとる。(5+7)÷2=6。",
    category: "度数分布とヒストグラム・代表値",
  },

  // 近似値・誤差・有効数字
  {
    text: "測定などによって得られた、真の値に近い値を何という？",
    type: "choice",
    answer: "近似値",
    choices: ["近似値", "真の値", "誤差", "有効数字"],
    explain: "近似値は、真の値そのものではなく、それに近い値。",
    category: "近似値・誤差・有効数字",
  },
  {
    text: "近似値から真の値を引いた差を何という？",
    type: "choice",
    answer: "誤差",
    choices: ["誤差", "近似値", "真の値", "有効数字"],
    explain: "誤差 = 近似値 - 真の値。",
    category: "近似値・誤差・有効数字",
  },
  {
    text: "測定値のうち、信頼できる数字を何という？",
    type: "choice",
    answer: "有効数字",
    choices: ["有効数字", "近似値", "誤差", "真の値"],
    explain: "有効数字は、測定によって得られた信頼できる桁の数字。",
    category: "近似値・誤差・有効数字",
  },
  {
    text: "真の値がa、近似値がbのとき、誤差を表す式はどれ？",
    type: "choice",
    answer: "b-a",
    choices: ["b-a", "a-b", "a+b", "a÷b"],
    explain: "誤差 = 近似値(b) - 真の値(a)。",
    category: "近似値・誤差・有効数字",
  },
  {
    text: "ある長さを測ったところ、近似値は15.3cmで、真の値は15.0cmであった。誤差は何cm？",
    type: "numeric",
    answer: 0.3,
    explain: "誤差 = 近似値 - 真の値 = 15.3 - 15.0 = 0.3cm。",
    category: "近似値・誤差・有効数字",
  },
  {
    text: "12000という数を、有効数字4桁として a×10ⁿ の形で表すと？",
    type: "choice",
    answer: "1.200×10⁴",
    choices: ["1.200×10⁴", "1.2×10⁴", "12×10³", "0.12×10⁵"],
    explain: "有効数字4桁を表すには、1.200のように末尾の0も書いて桁数をそろえる。",
    category: "近似値・誤差・有効数字",
  },
];
